#cloud-config
package_update: true
package_upgrade: true
packages:
- htop
- vim
- curl
- wget
- git
- ufw # optional firewall management

runcmd:
# Basic firewall (optional)
- ufw allow ssh
- ufw --force enable

# Test əmrləri
- echo "Bastion VM ready"
